export const REMINDER_SETTINGS_REQUESTS = 'REMINDER_SETTINGS_REQUESTS';
export const REMINDER_SETTINGS_SUCCESS = 'REMINDER_SETTINGS_SUCCESS';
export const REMINDER_SETTINGS_ERROR = 'REMINDER_SETTINGS_ERROR';
